apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  template:
    metadata:
      name: app-pod
      labels:
        app: app-pod
    spec:
      containers:
        - name: app-container
          image: rafanercessian/aplicacao-loja:v1
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: app-pod #igual nome labels metadata linha 10
